#!/bin/bash

relation-set domain='example.com'
relation-set resources='@ IN NAPTR 1 1 "S" "SIP+D2T" "" _sip._tcp
@ IN NAPTR 2 1 "S" "SIP+D2U" "" _sip._udp
_sip._tcp IN SRV 0 0 5060 bono-$id'
# _sip._udp IN SRV 0 0 5060 bono-$id'

NAMESERVER=`relation-get public-address`
echo "nameserver $NAMESERVER" >> /etc/resolvconf/resolv.conf.d/head
service resolvconf restart